name: Run Playwright Tests on VPS

on:
  push:
    branches:
      - ismail

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into VPS and Run Tests
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_IP << 'EOF'
            set -e  # Exit immediately if any command fails
            cd /home/hurayra/playwright-automation-essential-blocks
            git pull origin ismail || { echo "Git pull failed"; exit 1; }
            npx playwright test tests/advanced*
            TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
            REPORT_DIR=/var/www/playwright-reports/$TIMESTAMP
            mkdir -p $REPORT_DIR
            cp -r playwright-report/* $REPORT_DIR
          EOF
